{% set name = "dynaconf" %}
{% set version = "3.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d79e0189d97b3f226b8ebb1717e2ce05d1a05cdf6ea05de66d24625fdb5a0cbd

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - dynaconf=dynaconf.cli:main

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python

test:
  imports:
    - dynaconf
  requires:
    - pip
  commands:
    - pip check
    - dynaconf --help

about:
  home: https://www.dynaconf.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Configuration Management for Python
  description: Configuration Management for Python
  doc_url: https://www.dynaconf.com/
  dev_url: https://github.com/dynaconf/dynaconf

extra:
  recipe-maintainers:
    - carlodri
