{% set name = "dynaconf" %}
{% set version = "3.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9cfb50fd4a71a543fd23845d4f585b620b6ff6d9d3cc1825c614f7b2097cb39

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dynaconf = dynaconf.cli:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - setuptools >=38.6.0
    - python >=3.7

test:
  imports:
    - dynaconf
  commands:
    - dynaconf --help

about:
  home: https://www.dynaconf.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Configuration Management for Python.
  doc_url: https://www.dynaconf.com/
  dev_url: https://github.com/rochacbruno/dynaconf

extra:
  recipe-maintainers:
    - carlodri
